---
# tasks file for security
- name: Disable password authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: "PasswordAuthentication {{ ssh_password_authentication }}"
    validate: 'sshd -t -f %s'
  notify: Reload sshd

- name: Ensure SELinux is in enforced mode
  ansible.posix.selinux:
    policy: targeted
    state: "{{ selinux_state }}"

- name: Ensure firewalld is running and enabled
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true